# Generated by Django 5.1.1 on 2024-12-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(default='sick'),
            preserve_default=False,
        ),
    ]
