# Generated by Django 5.1.1 on 2024-11-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('view_dashboard', 'Can view dashboard')]},
        ),
        migrations.AddField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctors'),
        ),
    ]
